name: W3C Trace Context Integration Test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
          node-version: 18

      - name: Install and Bootstrap 🔧
        run: npm ci

      - name: Generate version.ts files
        run: npm run version:update

      - name: Build 🔧
        run: npm run compile
        working-directory: ./integration-tests/propagation-validation-server

      - name: Run W3C Test harness
        run: ./integration-tests/tracecontext-integration-test.sh
